sudo: required
services: [docker]
before_install:
  [docker build -t xtophe02/react-test -f ./client/Dockerfile.dev ./client]
script: [docker run xtophe02/react-test npm run test -- --coverage]
after_success:
  - docker run -t "xtophe02/multi-client:v1" ./client
  - docker run -t "xtophe02/multi-nginx:v1" ./nginx
  - docker run -t "xtophe02/multi-server:v1" ./server
  - docker run -t "xtophe02/multi-worker:v1" ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push "xtophe02/multi-client:v1"
  - docker push "xtophe02/multi-nginx:v1"
  - docker push "xtophe02/multi-server:v1"
  - docker push "xtophe02/multi-worker:v1"
